### ISSUE TITLE
[Bug] Freezing Trap and Explosive Trap won't trigger

### ISSUE THREAD

**Issue by WowSporkles** [demilich1/metastone#88] opened 2016-03-06 02:16 UTC
Using version 1.0.1 and Freezing Trap will not trigger when attacking a minion or a hero. Explosive Trap also won't trigger.

**Comment by webadict** [comment] 2016-03-06 02:22
I just used Freezing Trap in 1.0.1 to find a different bug, so that's
really confusing. Can you elaborate on what you did?

**Comment by WowSporkles** [comment] 2016-03-06 02:23
I used Sandbox mode to add a Freezing Trap to my hand, then had the opponent attack a minion and my face. It triggered neither time.

**Comment by WowSporkles** [comment] 2016-03-06 02:30
I just tried reinstalling version 1.0.1 and the same bug still applied.

**Comment by webadict** [comment] 2016-03-06 04:00
... Now I'M confused! I literally tested it because the Card .getCopy() function was working incorrectly!

Alright, let's figure this out...

**Comment by webadict** [comment] 2016-03-06 04:05
...Wait. I have an idea what might have caused this...

**Comment by webadict** [comment] 2016-03-06 04:55
Yeah, I'm right... Unfortunately, re-aligning all of the Events and Triggers caused a disconnect with PhysicalAttackTrigger, since it really needs both player ids... Unfortunate, really. This is probably true of all triggers that require multiple player ids (Source + Target Player). They're using the same player id to check, I'm fairly certain.

I'll see what I can do...

**Comment by webadict** [comment] 2016-03-06 19:28
Alright it will be fixed in the next PR. The issue was that the target Player's id was being used when checking the source Player. In some secrets, this did nothing, because the source player was set in a way that it shouldn't, but in some cases, this broke the secret.

All cases of source player should now work as intended.

**Closed** 2016-03-08 12:35 UTC
Labels: bug
