### ISSUE TITLE
Brann Bronzebeard and Golden Monkey causes fatal error

### ISSUE THREAD

**Issue by OwenNash** [demilich1/metastone#288] opened 2016-12-05 14:25 UTC
It looks like Brann's trigger causes an error when Golden Monkey is played.

-----------

14:07:24 ERROR - Id 78 not found!
14:07:24 ERROR - {PENDING_CARD=[EntityReference id:68], LAST_MANA_COST=4, SUMMON_REFERENCE_STACK=[[EntityReference id:71]], EVENT_TARGET_REFERENCE_STACK=[]}
14:07:28 ERROR - Error while processing gameEvent net.demilich.metastone.game.events.SummonEvent@4c012b31
14:07:28 ERROR - =========PANIC DUMP=========
14:07:28 ERROR - ERROR while playing card [MINION 'Golden Monkey' [EntityReference id:68] Manacost:4] reference: [CardReference playerId:0 cardName:Golden Monkey cardLocation:HAND cardId:68]
14:07:28 ERROR - =========PANIC DUMP=========
java.lang.RuntimeException: Target not found exception: [EntityReference id:78]
	at net.demilich.metastone.game.logic.TargetLogic.findEntity(TargetLogic.java:116)
	at net.demilich.metastone.game.GameContext.resolveSingleTarget(GameContext.java:500)
	at net.demilich.metastone.game.spells.trigger.SpellTrigger.canFire(SpellTrigger.java:159)
	at net.demilich.metastone.game.spells.trigger.TriggerManager.fireGameEvent(TriggerManager.java:67)
	at net.demilich.metastone.game.GameContext.fireGameEvent(GameContext.java:151)
	at net.demilich.metastone.gui.playmode.GameContextVisualizable.fireGameEvent(GameContextVisualizable.java:44)
	at net.demilich.metastone.game.logic.GameLogic.summon(GameLogic.java:1671)
	at net.demilich.metastone.game.actions.PlayMinionCardAction.play(PlayMinionCardAction.java:41)
	at net.demilich.metastone.game.actions.PlayCardAction.execute(PlayCardAction.java:44)
	at net.demilich.metastone.game.logic.GameLogic.performGameAction(GameLogic.java:1212)
	at net.demilich.metastone.game.GameContext.performAction(GameContext.java:393)
	at net.demilich.metastone.game.GameContext.playTurn(GameContext.java:455)
	at net.demilich.metastone.game.GameContext.play(GameContext.java:402)
	at net.demilich.metastone.gui.sandboxmode.commands.CreateNewSandboxCommand$1.run(CreateNewSandboxCommand.java:46)
	at java.lang.Thread.run(Thread.java:745)

**Comment by webadict** [comment] 2016-12-05 16:28
This should be fixed in the PR. This is an issue caused by replacing a minion with a DeckTrigger.

**Closed** 2016-12-06 19:23 UTC
