### ISSUE TITLE
[Knife Juggler] - overkilling with trigger

### ISSUE THREAD

**Issue by demilich1** [demilich1/metastone#91] opened 2016-03-07 10:15 UTC
Bug report received via email:

In certain cases Knife Juggler is still hitting dead minions when triggered by Haunted Creeper's Deathrattle. For example, if a 1/2 Haunted Creeper attacks into a 2/1 minion, Metastone will correctly ignore the 2/1 minion and send each dagger somewhere else. However, if a 1/2 Haunted Creeper attacks into a 2/2 minion, both daggers will sometimes hit that minion, overkilling it by 1. This also happens with Knife Juggler + Implosion.

Most probably this is not an issue specific to Knife Juggler, but affects all deal-damage-when-something-happens triggers.

**Comment by mayuso** [comment] 2016-03-07 10:53
> Most probably this is not an issue specific to Knife Juggler, but affects all deal-damage-when-something-happens triggers.

I agree, this is most likely a mechanic bug and not a specific card bug, maybe checking if the target minion is dead after each damage point is done could solve all the problems at once.

**Comment by webadict** [comment] 2016-03-07 14:52
I have an idea on what might fix this, as you're both right. I'll do some testing, but it's probably a lot easier than we might think, since messing around with some of the death targeting mechanics is a bad idea.

**Comment by webadict** [comment] 2016-03-07 15:01
And I think that worked. Basically... We just make Knife Jugglers use MissilesSpell instead of DamageSpell! Since Missiles are inherently built to ignore targets that are mortally wounded, we can switch Knife Jugglers to do the same thing, since multiple summoning events basically acts as a Missiles Spell, but without checking for mortally wounded status in between, which we wouldn't want to do anyway for a lot of reasons (Explosive Sheep is a good one, which shouldn't check for mortally wounded status when applying damage to something like an Acolyte of Pain.)

This should probably happen for a lot of minions that have on summon effects that deal damage, but Knife Juggler is the most common. The issue is that no other minion I can think of would be able to appropriately do the same thing.

So, fixed in next PR!

**Closed** 2016-03-08 12:35 UTC
Labels: bug
