### ISSUE TITLE
[Emperor Thaurissan]

### ISSUE THREAD

**Issue by demilich1** [demilich1/metastone#178] opened 2016-06-18 06:47 UTC
Received via email:

_If Emperor Thaurissan's trigger goes off while your hand is empty, Metastone will reduce the mana cost of each card you draw by 1. This will continue occurring even if Thaurissan is destroyed._

**Comment by webadict** [comment] 2016-06-18 14:06
Lol, what? I think I know where it does this, I just have no idea why. I'll
check it on Sunday.

**Comment by demilich1** [comment] 2016-06-19 07:40
I am in a hurry right now, don't have time today, but will add a unit test for this bug on Monday. 'Tis a funny one btw :wink:

**Comment by demilich1** [comment] 2016-06-20 14:33
Previously this was implemented slightly different if I remember correctly. The manacost reduction would be stored as an attribute on each card. What was the reason you changed the implementation, is it because of Shifter Zerus?

**Comment by webadict** [comment] 2016-06-20 14:40
No, it was actually because of a certain trifling gnome, Wilfred Fizzlebang. He needed to have a specific card targeted, but it wasn't working as intended. Thaurissan had his own unique spell at the time, which was only used by him, so I cut the spell and merged the two, since it didn't really gain anything from it.

I had to do a little rewriting of the CardCostModifier class so that it would allow things like that, which made it easier to implement for Emperor as well. Shifter Zerus still doesn't work correctly, but... it might if I simply switch the ID on the transformed card to the old ID... No idea if this would break anything related to it, but it certainly fixes the card cost issues (Heck, it might even be doable with bonus attack/hp, though Shadowcastering a Shifter Zerus still needs to wait until the Buff Update.)

**Comment by webadict** [comment] 2016-06-20 14:55
Oh right, I also remember a few of the other issues that cost modifiers had that were fixed: Thaurissan not working with Aviana/Sea Witch, plus a few other issues. The changes fixed all of that as well.

**Comment by demilich1** [comment] 2016-06-20 16:08
Why would it not work for Fizzlebang to set the MANA_COST_MODIFIER of the drawn card to -99?

**Comment by webadict** [comment] 2016-06-20 16:15
Several reasons, many that are fringe cases and some hypothetical.

The biggest issue is Loatheb. Any spell set to zero should cost 5. Another
is Mana Wraith. Both of these cases would fail, and cost zero instead.

Hypothetically, playing a card that increases the cost of cards in your
hand after Wilfred should set the cost to the increase, but wouldn't if it
were set to -99.

Because that's essentially what it does. Any modifiers afterward set it to
-90 something, which is incorrect.

**Closed** 2016-06-20 16:14 UTC
Labels: bug

**Comment by demilich1** [comment] 2016-06-20 16:16
@webadict Could you please review my commit https://github.com/demilich1/metastone/commit/9d9c58a2758c01991c859059a343a186277f948d to see if you spot any error?
