### ISSUE TITLE
[Improvement] Arcane Missiles

### ISSUE THREAD

**Issue by SirFatCat** [demilich1/metastone#40] opened 2015-11-30 02:44 UTC
The main issue with Arcane Missiles is that it shows -1 Health on anything it hits, even if it hits the target more than once. It can be quite confusing sometimes.

**Comment by mayuso** [comment] 2015-11-30 07:24
What do you mean, health can go below 0? Or every time it hits it shows "-1"(For example, hit a 3 health minion and instantly -1 health)?

**Comment by SirFatCat** [comment] 2015-11-30 08:34
No, I mean. Arcane Missiles works as intended. It's just, visually, even if it hits something twice with the 1 damage it will show "-1" over the monster, rather than a "-2".

**Comment by mayuso** [comment] 2015-11-30 09:03
Then that´s not working as intended, if something is dead (AKA 0 hp (With exceptions)), arcane missiles is not supposed to hit it, right?

**Comment by SirFatCat** [comment] 2015-11-30 11:11
No problem, hope it isn't a pain to fix. :)

**Comment by webadict** [comment] 2015-11-30 18:36
This is more of an issue with not being able to fully adopt all the little things that Hearthstone does. On one hand, this would help clarify some things, but on the other, it could cause confusion.

Hearthstone has the advantage here, in that they have a nicely generated board and time delays and animations and so on. They are free to deal 1 damage at a time (Use this video as an example: https://www.youtube.com/watch?v=BCKcWjACPaE&noredirect=1) Since it updates slowly, 1 damage one at a time is very clear to the players.

There's one big issue that stands out to me, though: It is also confusing. An issue comes with something like Flamewaker, which shows the damage at the same time, so now a spell that looks like it did 6 damage might show 8 damage on an enemy and might be confused for a bug.

However, I do have an alternative that might work slightly better. It's used in a lot of different games, but the only one that comes to mind is Runescape. When attacked several times in a short span, you'll received several damage blurbs at once, and each one contains the damage information of an individual hit. So, being hit by two Arcane Missiles would show two -1s instead. This could be capped at a certain amount, and then even added to by using an extra blurb for additional hits that are tallied together. This way minimizes confusion and allows for less hidden information in the simulator.

Just knowing what I know about parts of the game, I might be able to do that, but I wouldn't start doing it for a while.

**Comment by SirFatCat** [comment] 2015-11-30 23:13
I'd be fine with multiple blobs, but I'm not sure I understand how it could be confusing. If you have Flamewaker and use Arcane Missiles, and both of them hit the same target 3 times with their individual blasts, then it should show a -3 and the other sources of damage should bring the total to -5, since that's how it works. I mean, if you have 8 damage on the board when you cast a spell that deals 6 damage, and you wonder where the extra 2 damage comes from, it'd be logical to piece together 2 damage to Flamewaker which you had played at an earlier turn. Personally I would be fine with it, since as long as you're aware of the board state, you should be able to remember the Flamewalker. I mean, most people would use the Flamewalker to try and make more plays than to just forget it and throw out a spell, haha.

**Comment by webadict** [comment] 2015-11-30 23:43
The math typically isn't difficult, but seeing all the damage sources merged together is confusing, since there is no clarity of source. The numbers would add up, but that's about it. That's still going to cause confusion for some players, since it's not working like the game would, which is the overall goal of the project.

**Comment by SirFatCat** [comment] 2015-12-01 04:38
I don't know, I don't see anyone really being confused as long as they've used Arcane Missiles before. Those who have used it know how it works, and probably know the interactions it has with other cards. I think currently it's the most confusing it can be, and with the blurb method you suggested it could get hectic considering you can get cards like Malygos out with an Arcane Missiles and that would add a lot of blurbs to the field. I think letting the damage stack would be the best way for it to look in a way that's not confusing, since Metastone probably won't be doing it individually like Hearthstone.

**Comment by demilich1** [comment] 2016-01-11 14:15
Implemented: Each damage event should now receive its own 'bubble' with a slight offset to the last one.

**Closed by demilich1** 2016-01-11 14:15 UTC
Labels: improvement
